#%RAML 1.0 Trait

headers:
  X-Cms-ClientId:
    required: true
    type: string
    example: "732672354-uewhh-3248723-37y3rjhfh"
  X-Cms-ClientSecret:
    required: true
    type: string
    example: "732672354-uewhh-3248723-37y3rjhfh"
