#%RAML 1.0 Trait

queryParameters:
  email:
    type: string
    required: false
    example: "abc@gmail.com"
  phonecountry:
    type: string
    required: false
    example: "+91"
  phonenumber:
    type: string
    required: false
    example: "9787876565"
  registrationDate:
    type: string
    required: false
    example: "20-05-2023"